### ISSUE TITLE
Can't overwrite object with same name

### ISSUE THREAD

**Issue by D4rk4** [storj/gateway-st#27]
Nov 25 20:31:27 s3io gateway[3530]: 2020-11-25T20:31:27.235+0100        ERROR        gateway error:        {"error": "uplink: metainfo error: unable to commit object", "errorVerbose": "uplink: metainfo error: unable to commit object\n\tstorj.io/uplink/private/metainfo.(*Client).CommitObject:495\n\tstorj.io/uplink/private/storage/streams.(*streamStore).Put:329\n\tstorj.io/uplink/private/storage/streams.(*shimStore).Put:53\n\tstorj.io/uplink/private/stream.NewUpload.func1:48\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
Nov 25 20:31:27 s3io gateway[3530]: API: PutObject(bucket=xxxx, object=xxxx/dvr.index)                                                                                            
Nov 25 20:31:27 s3io gateway[3530]: Time: 20:31:27 CET 11/25/2020
Nov 25 20:31:27 s3io gateway[3530]: DeploymentID: 9e5c94f2-9b06-4f0a-bec7-a741f585348f
Nov 25 20:31:27 s3io gateway[3530]: RequestID: 164AD7115FEEA583
Nov 25 20:31:27 s3io gateway[3530]: RemoteHost: 127.0.0.1
Nov 25 20:31:27 s3io gateway[3530]: Host: s3io.xxxx.tv
Nov 25 20:31:27 s3io gateway[3530]: Error: uplink: metainfo error: unable to commit object (*errs.errorT)                                                                                    
Nov 25 20:31:27 s3io gateway[3530]:        4: /go/pkg/mod/github.com/minio/minio@v0.0.0-20201028162317-be7f67268d1e/cmd/api-errors.go:1979:cmd.toAPIErrorCode()                              
Nov 25 20:31:27 s3io gateway[3530]:        3: /go/pkg/mod/github.com/minio/minio@v0.0.0-20201028162317-be7f67268d1e/cmd/api-errors.go:2004:cmd.toAPIError()                                  
Nov 25 20:31:27 s3io gateway[3530]:        2: /go/pkg/mod/github.com/minio/minio@v0.0.0-20201028162317-be7f67268d1e/cmd/object-handlers.go:1551:cmd.objectAPIHandlers.PutObjectHandler()     
Nov 25 20:31:27 s3io gateway[3530]:        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()  

> Release build
> Version: v1.1.9
> Build timestamp: 28 Oct 20 19:43 CET
> Git commit: 4585d016a79c4c1cc52e56b7a15904b226d06037

**Comment by wthorp** [comment]
Hi D4rk4, this issue seems to have "fallen through the cracks" for a bit.  I wasn't able to recreated it, and the particular error message you saw doesn't exist in our code anymore.  Are you still having this problem?
