### ISSUE TITLE
successful puts (1) less than or equal to repair threshold  (6)

### ISSUE THREAD

**Issue by 630141456** [storj/gateway-st#34]
gateway/0                                 12:02:56.436 | ERROR	miniogw/logging.go:59	gateway error:	{"error": "uplink: stream error: ecclient error: successful puts (1) less than or equal to repair threshold (6)", "errorVerbose": "uplink: stream error: ecclient error: successful puts (1) less than or equal to repair threshold (6)\n\tstorj.io/uplink/private/ecclient.(*ecClient).put:194\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutSingleResult:69\n\tstorj.io/uplink/private/storage/streams.(*Store).Put:242\n\tstorj.io/uplink/private/stream.NewUpload.func1:47\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
                                                       | storj.io/gateway/miniogw.(*layerLogging).log
                                                       | 	/root/gateway-st-main/miniogw/logging.go:59
                                                       | storj.io/gateway/miniogw.(*layerLogging).PutObject
                                                       | 	/root/gateway-st-main/miniogw/logging.go:117
                                                       | github.com/minio/minio/cmd.(*webAPIHandlers).Upload
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/web-handlers.go:1310
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.httpTraceHdrs.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/handler-utils.go:375
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setRedirectHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:135
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.addCustomHeaders.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:664
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.addSecurityHeaders.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:673
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setBucketForwardingHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:547
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setRequestValidityHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:535
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setHTTPStatsHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:469
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:49
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:68
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/crossdomain-xml-handler.go:51
                                                       | github.com/minio/minio/cmd.setBrowserRedirectHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:161
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setReservedBucketHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:293
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:262
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setTimeValidityHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:357
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:456
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setAuthHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/auth-handler.go:499
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.setSSETLSHandler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:707
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.filterReservedMetadata.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:108
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/gorilla/mux.(*Router).ServeHTTP
                                                       | 	/root/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
                                                       | github.com/rs/cors.(*Cors).Handler.func1
                                                       | 	/root/gopath/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/generic-handlers.go:692
                                                       | github.com/minio/minio/cmd/http.(*Server).Start.func1
                                                       | 	/root/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20210304002810-c3217bd6ebc0/cmd/http/server.go:101
                                                       | net/http.HandlerFunc.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2069
                                                       | net/http.serverHandler.ServeHTTP
                                                       | 	/root/go/src/net/http/server.go:2887
                                                       | net/http.(*conn).serve
                                                       | 	/root/go/src/net/http/server.go:1952

**Comment by 630141456** [comment]
nobody

**Comment by wthorp** [comment]
The error " successful puts (1) less than or equal to repair threshold" is caused when the uploading files to the Storj network.  It may happen occasionally due to network issues.  If you're seeing it repeatedly, it's most likely due to networking / firewall issues: the "uplink" client within Gateway-ST can't establish and/or hold connection to remote "storage nodes".
