### ISSUE TITLE
S3 Gateway: GetBucketAcl not implemented

### ISSUE THREAD

**Issue by paulerickson** [storj/gateway-st#47]
I'm getting an error response when getting trying to get a bucket's ACL

```sh
aws s3api --endpoint=http://localhost:7777/ --profile=local-tardigrade get-bucket-acl --bucket test-bucket      

An error occurred (NotImplemented) when calling the GetBucketAcl operation: A header you provided implies functionality that is not implemented
```

Likewise when I click Policy from the web UI:
![Screenshot from 2020-02-20 13-17-24](https://user-images.githubusercontent.com/50889/74970108-6f682800-53e3-11ea-8479-c45d0d1746bf.png)

**Comment by wthorp** [comment]
At this time, we don't support Bucket ACLs with Storj, as it implies a system of Access Controls that it implies system like AWS's IAM (Identity and Access Management) which we believe is beyond the scope of typical S3 integration.  ACLs differ substantially from the main security system of the Storj network, macaroons (see https://www.storj.io/blog/flexible-file-sharing-with-macaroons).

I'd be curious to understand more about your use case, if you think there is still some value in the GetBucketACL endpoint.

**Comment by paulerickson** [comment]
I don't follow—I didn't use IAM above with minio, only the S3 API.  This project is described as S3 compatible, but the `NotImplemented` behavior breaks compatibility.  So, you could not, for instance, use Storj as a [blob store for Nexus Repository Manager](https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management/configuring-blob-stores).

**Comment by wthorp** [comment]
I've looked into this further and think I understand your perspective better with the Nexus reference.  Gateway-ST currently doesn't support GetLifecycleConfiguration, PutLifecycleConfiguration, or GetBucketAcl, which are stated as required by https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management/configuring-blob-stores.

The Storj Gateway implementation is derived from https://github.com/minio/minio/blob/master/cmd/gateway-unsupported.go and thus returns a NotImplemented response for unsupported endpoints.  It shouldn't be difficult for us to return a default / "empty" response for GetBucketAcl and GetLifecycleConfiguration instead.  I appreciate the idea and I suspect we can get this out in the current 2-week sprint.

To genuinely implement PutLifecycleConfiguration, however, requires features that are not planned for our backend.  Are you familiar enough with Nexus to know what features of PutLifecycleConfiguration it leverages?
