### ISSUE TITLE
Is there any way to have multiple s3 users

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#60]
Hey folks, I'm aware that the StorJ gateway-st is not a full s3 full compatible solution, the support for multiple users, CORS and policies is quite limited. Still, I'm wondering if there is any chance that I have multiple logins, maybe with a 3rd party software? I don't need any further rights management, as the most stuff can be done at the Storj DCS while limiting the access grant.

Very thankful for any good hint.

**Comment by venomone** [comment]
I'm fine with the fact that I can't set any policy onto a user, I don't need this for the moment, but a quick a dirty workaround would be nice for multiple users credentials. I mean, at the go code, there must be a way for a simple "for loop" mechanism or something like that to go through a list of users in a text file or so.

**Comment by halkyon** [comment]
Hi @venomone!

You could use [Gateway-MT](https://github.com/storj/gateway-mt) which is designed to run multi-tenant, with many users and credentials accessing the same service. You could use the [Storj hosted](https://docs.storj.io/dcs/getting-started/gateway-mt/) service, or run it yourself if desired. Alternatively, you could run a Gateway-ST per user/credential, although I understand that might be unwieldy, especially if there's many users/credentials involved.

Gateway-ST is built on top of Minio, so there may be a way of utilizing multiple credentials using Minio, but we'd need to investigate this one a bit further.

**Comment by venomone** [comment]
@halkyon first, thanks for your quick reply :)
I was confused about the Gateway-MT and what it actually is. From my understanding, I can manage multiple access grants and not multiple s3 users?! Would be awesome if you guys could add some more details onto the differences between gateway-st / mt and how to set it up as the docs a quite unclear to me.

**Comment by venomone** [comment]
My bad, I checked the docs again
