### ISSUE TITLE
Downloading larger files fails with context canceled

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#61]
Hey folks, im running on the following Storj gateway-st version (currently the latest):
<pre>
Release build
Version: v1.6.1
Build timestamp: 25 Feb 22 17:10 UTC
Git commit: 85e616645a2d48887f68f335a5a823cd31fdd42a

</pre>

### What operating system and processor architecture are you using (`uname -mrsv`)?

<details><summary><code>uname -mrsv</code> Output</summary><br><pre>
Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64
</pre></details>

### What did you do?

Downloading a large file (at least 3 GB) using the gateway-st

### What did you expect to see?

An uncorrupted file, as currently every larger file download gets corrupted

### What did you see instead?

If I check onto my console, I get the following error while download a larger file (this appears at a random position of the download, most of the time near the end of the actual transfer). Besides, it seems that this issue only occours when using multipart download:

```
Error: Unable to write all the data to client uplink: eestream: failed to download stripe 0: 
    error retrieving piece 03: context canceled
    error retrieving piece 101: drpc: stream terminated by sending close
    error retrieving piece 103: drpc: stream terminated by sending close
    error retrieving piece 105: ecclient: piecestore: rpc: context canceled
    error retrieving piece 109: io: read/write on closed pipe
    error retrieving piece 22: context canceled
    error retrieving piece 30: context canceled
    error retrieving piece 41: context canceled
    error retrieving piece 63: context canceled
    error retrieving piece 70: context canceled
    error retrieving piece 88: drpc: stream terminated by sending close
    error retrieving piece 98: context canceled (*fmt.wrapError)
           2: /go/pkg/mod/storj.io/minio@v0.0.0-20220215210608-f35d7bc00e6e/cmd/object-handlers.go:517:cmd.objectAPIHandlers.GetObjectHandler()
           1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```
Sometimes I also get this:
```

Error: uplink: stream: metaclient: metabase: pending object missing (*errs.errorT)
           4: /go/pkg/mod/storj.io/minio@v0.0.0-20220215210608-f35d7bc00e6e/cmd/api-errors.go:2023:cmd.toAPIErrorCode()
           3: /go/pkg/mod/storj.io/minio@v0.0.0-20220215210608-f35d7bc00e6e/cmd/api-errors.go:2048:cmd.toAPIError()
           2: /go/pkg/mod/storj.io/minio@v0.0.0-20220215210608-f35d7bc00e6e/cmd/object-handlers.go:2706:cmd.objectAPIHandlers.PutObjectPartHandler()
           1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

Additional Information:

I'm running the gateway-st behind a nginx reverse proxy, but the setup is pretty straight forward and basically working well:
```
        location / {
            proxy_buffer_size 16k;
            proxy_buffers 8 16k;
            proxy_busy_buffers_size 32k;
            proxy_cache_convert_head off;
            proxy_connect_timeout 300s;
            proxy_hide_header Set-Cookie;
            proxy_hide_header x-amz-id-2;
            proxy_hide_header x-amz-request-id;
            proxy_http_version 1.1;
            proxy_ignore_headers Set-Cookie;
            proxy_pass http://127.0.0.1:7777;
            proxy_read_timeout 3600s;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_session_reuse on;
        }
```

**Comment by amwolff** [comment]
Hi @venomone! Thanks for reporting this issue. Have you tried to isolate it by running the same test without the reverse proxy? This would make us sure the problem is somewhere in the gateway/its dependencies and not in the setup.

**Comment by venomone** [comment]
I digged in some deeper and was able to isolate something very, very strange and currently I don't think it has anything to do with the Gateway itself nor with my NGINX Proxy, instead I guess it has something to do with ClouFlare, this is maybe also very interesting for other users:

I Host the Gateway on several high performance machines, If you have a Loadbalancer with Cloudflare it initially works fine, After some time, Cloudflare starts blocking multipart upload requests for whatever reason ... Most likely their traffic Analytics AI or similar, please read on...

If you disable the Cloudflare proxy (Orange Cloud Icon switch at the Cloudflare dashboard) and simply start using the gateway for a couple of multipart up and downloads, maybe for 1-2 hrs or so then you can re-enable the Cloudflare proxy and don't run into any strange behaviors. From my understanding Cloudflare automatically analysis how your services acts in terms of your url structure and if this does not fit into the basic ruleset their systems blocks you after some time. So my Idea here was to simply make the CloudFlare System learn how my system acts by disabling the CloudFlare reverse proxy function and for some reason it simply works now. Only took me 2 days to understand whats going on here. Good luck

**Comment by amwolff** [comment]
> If you disable the Cloudflare proxy (Orange Cloud Icon switch at the Cloudflare dashboard) and simply start using the gateway for a couple of multipart up and downloads, maybe for 1-2 hrs or so then you can re-enable the Cloudflare proxy and don't run into any strange behaviors. From my understanding Cloudflare automatically analysis how your services acts in terms of your url structure and if this does not fit into the basic ruleset their systems blocks you after some time or at least some specific requests according to multipart uploads. So my Idea here was to simply make the CloudFlare System learn how my system acts by disabling the CloudFlare reverse proxy function and for some reason it simply works now with re-enable cloudflare proxy. Only took me 2 days to understand whats going on here. Good luck

This is very interesting/useful. Thank you so much for sharing!
