### ISSUE TITLE
Flaky rclone integration test

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-st#63]
Sometimes during an integration test on the CI, rclone tests fail when setting up: 

```
error code 141 in 46 gateway-st/testsuite/integration/rclone.sh line 6 :: RCLONE_VERSION=$(rclone version | head -n1 | awk '{ print $2 }')
script returned exit code 141
```

Examples:

* https://build.dev.storj.io/blue/organizations/jenkins/gateway-st-gerrit/detail/gateway-st-gerrit/1723/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/gateway-mt-gerrit/detail/gateway-mt-gerrit/4056/pipeline/

It can be resolved by running the build again until it passes, so it doesn't happen all the time.

**Comment by amwolff** [comment]
@halkyon I think this one is resolved, no?

**Comment by amwolff** [comment]
O yeah, here's the commit that resolved it: https://github.com/storj/gateway-st/commit/59eab7cb2926e255faa1772038005a4eb0db7c82 🎉
