### ISSUE TITLE
Invalid UI version in the JSON-RPC response

### ISSUE THREAD

**Issue by CatInAHatIsBack** [storj/gateway-st#65]
### What version of Gateway-ST are you using (`gateway version`)?

Unsure of how to commit a tree hash or a docker image digest.
<pre>
$ gateway version
Development build 
</pre>

### What operating system and processor architecture are you using (`uname -mrsv`)?
<details><summary><code>uname -mrsv</code> Output</summary><br><pre>
$ uname -mrsv
Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
</pre>

</details>

### What did you do?
- trying to setup the test network i followed the (https://github.com/storj/storj/wiki/Test-network) instructions, seems to be missing a few steps but got the storage-nodes working. tried connecting to gateway (http://127.0.0.1:11000/minio/login) but get :
<img width="856" alt="Screen Shot 2022-07-17 at 8 16 19 PM" src="https://user-images.githubusercontent.com/94614129/179398719-785df2ab-7d0a-407f-b019-ce3eeee13f6e.png">

- trying to set minio access and secret keys throught terminal gives following error

2022-07-17T20:09:01.191+0800	DEBUG	process/exec_conf.go:394	Unrecoverable error	{"error": "gateway configuration: failed parsing access config: uplink: invalid access grant format", "errorVerbose": "gateway configuration: failed parsing access config: uplink: invalid access grant format\n\tmain.checkCfg:183\n\tmain.cmdRun:163\n\tstorj.io/private/process.cleanup.func1.4:363\n\tstorj.io/private/process.cleanup.func1:381\n\tgithub.com/spf13/cobra.(*Command).execute:852\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:960\n\tgithub.com/spf13/cobra.(*Command).Execute:897\n\tstorj.io/private/process.ExecWithCustomConfig:88\n\tstorj.io/private/process.Exec:65\n\tmain.main:449\n\truntime.main:250"}

- unsure of where to go from here. there was a similar issue (https://github.com/storj/gateway-st/issues/59), but of little help.

**Comment by amwolff** [comment]
Hi @CatInAHatIsBack! Thanks for the report.

We are aware of the issue of the object browser not working for Gateway-ST started through storj-sim. However, it will correctly function if you grab the release binary from [the releases page](https://github.com/storj/gateway-st/releases). I will raise the issue of the malfunctioning object browser for Gateway-ST started through storj-sim internally.

One thing to note is that the object browser isn't for setting up credentials; it's only for operating on buckets and objects through a simple UI.

For the second issue, how are you trying to set credentials? Can you paste exact commands?

**Comment by CatInAHatIsBack** [comment]
`gateway run --minio.access-key 4Vfgr9g1jMFp26XVrdsx5AqzMHAB --minio.secret-key XXXXXXXXXXXXXXXXXX`
Does the release binary work for setting up the test-netwrok?

**Comment by halkyon** [comment]
If this helps, this is the command I use myself when running a release Gateway-ST for an existing storj-sim:

```
gateway run --access "$(storj-sim network env GATEWAY_0_ACCESS)" --minio.access-key "$(storj-sim network env GATEWAY_0_ACCESS_KEY)" --minio.secret-key "$(storj-sim network env GATEWAY_0_SECRET_KEY)" --server.address 127.0.0.1:7777
```
