### ISSUE TITLE
Quick question onto logging

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#74]
Hey folks,

I will skip the template for now, I hope thats fine. Im running the Gateway-ST inside docker, works like a charm, I'm having a lot of fun with it ;)
But one thing bothers me. As soon as my container starts, despite that it's fully working as intended, I get the following error from the Gateway:

```
| 
| API: SYSTEM()
| Time: 12:32:13 UTC 04/18/2023
| DeploymentID: 13b13fab-ac65-4f53-9229-129058b8ba37
| Error:  (cmd.NotImplemented)
|        5: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
|        4: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/auth-handler.go:345:cmd.CheckRequestAuthTypeCredential()
|        3: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/auth-handler.go:274:cmd.checkRequestAuthType()
|        2: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/object-handlers.go:344:cmd.ObjectAPIHandlers.GetObjectHandler()
|        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
| 
| API: SYSTEM()
| Time: 12:32:13 UTC 04/18/2023
| DeploymentID: 13b13fab-ac65-4f53-9229-129058b8ba37
| Error:  (cmd.NotImplemented)
|        3: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
|        2: /go/pkg/mod/storj.io/minio@v0.0.0-20221201234724-d0af19bf6813/cmd/object-handlers.go:359:cmd.ObjectAPIHandlers.GetObjectHandler()
|        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

Can somebody tell me how I can switch that off? I aware that the Gateway does not fully implement the S3 API, that's fine, but do I always need to see that error?

Thanks in advance.

**Comment by amwolff** [comment]
As Gateway-ST is just a storage backend for MinIO and a wrapper around it to start it more easily, we can't easily disable that logging. Until we replace MinIO with our in-house solution or use something more extensible, there will be things that we cannot control, unfortunately.

The only option I see for now is to try reconfiguring your application to not use parts of the S3 specification that we don't support (if that's possible).

**Comment by venomone** [comment]
Okay, I already was on the same track as you. So simply stick with the minio configs for the Moment.

About what inhouse solution are you talking about?
Is StorJ about to bring out a own s3 Gateway Implementation? Can't wait to try it :D

**Comment by amwolff** [comment]
There were more pressing issues so far, so we haven't pursued that, but this is certainly still on our tech debt reduction-related radar. 🙂
